language: java
jdk: oraclejdk8
before_script:
  - chmod +x  $TRAVIS_BUILD_DIR/src/Backend/IntegrationService/gradlew
  - chmod +x  $TRAVIS_BUILD_DIR/src/Backend/OrderService/gradlew
  - chmod +x  $TRAVIS_BUILD_DIR/src/Clients/gradlew
script: 
  - cd  $TRAVIS_BUILD_DIR/src/Backend/IntegrationService
  - ./gradlew build
  - cd  $TRAVIS_BUILD_DIR/src/Backend/OrderService
  - ./gradlew build test
  - cd  $TRAVIS_BUILD_DIR/src/Clients
  - ./gradlew build