version: "3"
services:
  mongo:
    image: jriniesta/p2gps:db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          #memory: 200M
      restart_policy:
          condition: none
    ports:
        - "28017"
        - "27017"
    volumes:
        - "db-data:/var/logs/"
  order:
    image: jriniesta/p2gps:order
    depends_on:
        - "mongo"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          #memory: 500M
      restart_policy:
          condition: none
    ports:
        - "8080"
  web:
    image: jriniesta/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          #memory: 300M
      restart_policy:
          condition: none
    ports:
        - "8082"
volumes:
    db-data:
      driver: azure_file
      driver_opts: 
        share_name: db-data
        storage_account_name: almacengpsidUnico
