name: CI con gradle 

on:
  push:
    branches: [ master ] # se ejecutará cuando hagamos un push a esta rama
  workflow_dispatch: #y también podremos ejecutar el workflow manualmente desde github
  
jobs:
  build:
    runs-on: ubuntu-latest # trabajaremos sobre una máquina ubuntu
    permissions:
      contents: read # el repositorio solo se puede leer
      packages: write # para tener acceso a los binarios resultantes de los build
      
    steps:
      #### CONFIGURACIÓN DEL ENTORNO jdk 8 y gradle 2.1 ####
      - uses: actions/checkout@v2 # descarga el repositorio en el ejecutor
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github #
          settings-path: ${{ github.worspace }}
      - name: set up gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 2.1
          
          
          ### BUILDS ###
          
      - name: hacer build del backend
        working-directory: src/Clients
        run: ./gradlew build
        
      - name: hacer build del backend
        working-directory: src/Backend/OrderService
        run: ./gradlew build test
