name: CI con gradle 

on:
  push:
    branches: [ master ] # se ejecutará cuando hagamos un push a esta rama
  workflow_dispatch: #y también podremos ejecutar el workflow manualmente desde github
  
jobs:
  build:
    runs-on: ubuntu-latest # trabajaremos sobre una máquina ubuntu
    permissions:
      contents: read # el repositorio solo se puede leer
      packages: write # para tener acceso a los binarios resultantes de los build
      
    steps:
      #### CONFIGURACIÓN DEL ENTORNO jdk 8 y gradle 2.1 ####
      - uses: actions/checkout@v2 # descarga el repositorio en el ejecutor
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github #
          settings-path: ${{ github.worspace }}
      - name: set up gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 2.1
          
          
          ### BUILDS ###
          
      - name: hacer build del backend
        working-directory: src/Clients
        run: ./gradlew build
        
      - name: hacer build del backend
        working-directory: src/Backend/OrderService
        run: ./gradlew build test


      - name: dockerizar el front y el backend
        run: | 
            cp src/Clients/build/libs/*.war deploy/docker/Clients/drop
            docker build -t p2gps/web deploy/docker/Clients
            cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop
            docker build -t p2gps/order deploy/docker/Order
            
      ### SUBIR IMÁGENES A DOCKERHUB ###
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Etiquetar con formato DockerHub
        run: |
          docker tag p2gps/web ${{secrets.DOCKERHUB_USERNAME }}/p2gps:web
          docker tag p2gps/web ${{secrets.DOCKERHUB_USERNAME }}/p2gps:order
      - name: Push a Dockerhub
        run: |
            docker push ${{secrets.DOCKERHUB_USERNAME }}/p2gps:order
            docker push ${{secrets.DOCKERHUB_USERNAME }}/p2gps:web
